Include link separately

diff --git a/.github/workflows/continuous-integration-workflow.yml b/.github/workflows/continuous-integration-workflow.yml
--- a/.github/workflows/continuous-integration-workflow.yml
+++ b/.github/workflows/continuous-integration-workflow.yml
@@ -48,7 +48,7 @@ jobs:
 #        if: ${{ failure() }}
         run: |
           echo "GITHUB_JOB is $GITHUB_JOB"
-          echo ":no_entry_sign: <https://github.com/$GITHUB_REPOSITORY/actions/runs/$JOB_ID/?check_suite_focus=true|*${GITHUB_JOB}*> failed" > job-$GITHUB_JOB.txt
+          echo ":no_entry_sign: *${GITHUB_JOB}* failed" > job-$GITHUB_JOB.txt
         env:
           JOB_ID: ${{ job.container.id }}
       - name: Export errors file
@@ -57,30 +57,6 @@ jobs:
         with:
           name: errors
           path: job-${{ github.job }}.txt
-      - name: Dump GitHub context
-          env:
-            GITHUB_CONTEXT: ${{ toJson(github) }}
-          run: echo "$GITHUB_CONTEXT"
-          - name: Dump job context
-            env:
-              JOB_CONTEXT: ${{ toJson(job) }}
-            run: echo "$JOB_CONTEXT"
-          - name: Dump steps context
-            env:
-              STEPS_CONTEXT: ${{ toJson(steps) }}
-            run: echo "$STEPS_CONTEXT"
-          - name: Dump runner context
-            env:
-              RUNNER_CONTEXT: ${{ toJson(runner) }}
-            run: echo "$RUNNER_CONTEXT"
-          - name: Dump strategy context
-            env:
-              STRATEGY_CONTEXT: ${{ toJson(strategy) }}
-            run: echo "$STRATEGY_CONTEXT"
-          - name: Dump matrix context
-            env:
-              MATRIX_CONTEXT: ${{ toJson(matrix) }}
-            run: echo "$MATRIX_CONTEXT"
 #  test_alternate_jdks:
 #    name: Test JDK 11 and 12
 #    runs-on: ubuntu-latest
@@ -290,6 +266,9 @@ jobs:
       - name: Alert Slack on build failure
         run: |
           cat job-*.txt > results.txt
+          echo "<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|Click here to view build>" >> results.txt
           results="$(cat results.txt)"
           jobFilesCount=$(ls . | grep 'job-.*\.txt' | wc -l)
-          (( $jobFilesCount > 1 )) && curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type":"header","text":{"type":"plain_text","text":"<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|CI build> failed for commit '"${COMMIT_SHA:0:9}"' on '${GITHUB_REF#refs/heads/}'"}},{"type":"section","text":{"type":"mrkdwn","text":"— _Author: '"$COMMIT_OWNER"'_"}}, {"type":"section","text":{"type":"mrkdwn","text":"\n '"$results"'"}}]}' "$SLACK_WEBHOOK_URL" || echo Slack message not sent, no errors to report
+          (( $jobFilesCount > 1 )) && curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type":"header","text":{"type":"plain_text","text":"CI build failed for commit '"${COMMIT_SHA:0:9}"' on '${GITHUB_REF#refs/heads/}'"}},{"type":"section","text":{"type":"mrkdwn","text":"— _Author: '"$COMMIT_OWNER"' $OWNER_LINK _"}}, {"type":"section","text":{"type":"mrkdwn","text":"\n '"$results"'"}}]}' "$SLACK_WEBHOOK_URL" || echo Slack message not sent, no errors to report
+        env:
+          OWNER_LINK: ${{ github.sender.html_url }}
