Use link jobs and build

diff --git a/.github/workflows/continuous-integration-workflow.yml b/.github/workflows/continuous-integration-workflow.yml
--- a/.github/workflows/continuous-integration-workflow.yml
+++ b/.github/workflows/continuous-integration-workflow.yml
@@ -23,7 +23,7 @@ jobs:
       - uses: actions/checkout@v2
       - name: Create initial results file
         run: |
-          echo "<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_JOB|Go to job> " > job-results.txt
+          touch job-results.txt
       - name: Export initial results file
         uses: actions/upload-artifact@v2
         with:
@@ -47,7 +47,7 @@ jobs:
       - name: Output failure
 #        if: ${{ failure() }}
         run: |
-          echo ":no_entry_sign: *${GITHUB_JOB}* failed" > job-$GITHUB_JOB.txt
+          echo ":no_entry_sign: <https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_JOB|*${GITHUB_JOB}*> failed" > job-$GITHUB_JOB.txt
       - name: Export errors file
 #        if: ${{ failure() }}
         uses: actions/upload-artifact@v2
@@ -265,4 +265,4 @@ jobs:
           cat job-*.txt > results.txt
           results="$(cat results.txt)"
           jobFilesCount=$(ls . | grep 'job-.*\.txt' | wc -l)
-          (( $jobFilesCount > 1 )) && curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type":"header","text":{"type":"plain_text","text":"CI build failed for commit '"${COMMIT_SHA:0:9}"' on '${GITHUB_REF#refs/heads/}'"}},{"type":"section","text":{"type":"mrkdwn","text":"— _Author: '"$COMMIT_OWNER"'_"}}, {"type":"section","text":{"type":"mrkdwn","text":"\n '"$results"'"}}]}' "$SLACK_WEBHOOK_URL" || echo Slack message not sent, no errors to report
+          (( $jobFilesCount > 1 )) && curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type":"header","text":{"type":"plain_text","text":"<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|CI build> failed for commit '"${COMMIT_SHA:0:9}"' on '${GITHUB_REF#refs/heads/}'"}},{"type":"section","text":{"type":"mrkdwn","text":"— _Author: '"$COMMIT_OWNER"'_"}}, {"type":"section","text":{"type":"mrkdwn","text":"\n '"$results"'"}}]}' "$SLACK_WEBHOOK_URL" || echo Slack message not sent, no errors to report
