Use markdown in title and adjust job id access

diff --git a/.github/workflows/continuous-integration-workflow.yml b/.github/workflows/continuous-integration-workflow.yml
--- a/.github/workflows/continuous-integration-workflow.yml
+++ b/.github/workflows/continuous-integration-workflow.yml
@@ -48,7 +48,9 @@ jobs:
 #        if: ${{ failure() }}
         run: |
           echo "GITHUB_JOB is $GITHUB_JOB"
-          echo ":no_entry_sign: <https://github.com/$GITHUB_REPOSITORY/actions/runs/$JOB_CONTAINER_ID/?check_suite_focus=true|*${GITHUB_JOB}*> failed" > job-$GITHUB_JOB.txt
+          echo ":no_entry_sign: <https://github.com/$GITHUB_REPOSITORY/actions/runs/$JOB_ID/?check_suite_focus=true|*${GITHUB_JOB}*> failed" > job-$GITHUB_JOB.txt
+        env:
+          JOB_ID = ${{ job.container.id }}
       - name: Export errors file
 #        if: ${{ failure() }}
         uses: actions/upload-artifact@v2
@@ -266,4 +268,4 @@ jobs:
           cat job-*.txt > results.txt
           results="$(cat results.txt)"
           jobFilesCount=$(ls . | grep 'job-.*\.txt' | wc -l)
-          (( $jobFilesCount > 1 )) && curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type":"header","text":{"type":"plain_text","text":"<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|CI build> failed for commit '"${COMMIT_SHA:0:9}"' on '${GITHUB_REF#refs/heads/}'"}},{"type":"section","text":{"type":"mrkdwn","text":"— _Author: '"$COMMIT_OWNER"'_"}}, {"type":"section","text":{"type":"mrkdwn","text":"\n '"$results"'"}}]}' "$SLACK_WEBHOOK_URL" || echo Slack message not sent, no errors to report
+          (( $jobFilesCount > 1 )) && curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type":"header","text":{"type":"mrkdwn","text":"<https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|CI build> failed for commit '"${COMMIT_SHA:0:9}"' on '${GITHUB_REF#refs/heads/}'"}},{"type":"section","text":{"type":"mrkdwn","text":"— _Author: '"$COMMIT_OWNER"'_"}}, {"type":"section","text":{"type":"mrkdwn","text":"\n '"$results"'"}}]}' "$SLACK_WEBHOOK_URL" || echo Slack message not sent, no errors to report
